name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, administrative ]
  pull_request:
    branches: [ main, administrative ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  # Setup and validation job
  setup:
    name: Setup and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Install Bazel (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update
          sudo apt install -y bazel

      - name: Install Bazel (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install bazel

      - name: Verify Bazel installation
        run: |
          bazel version
          bazel info

  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build all targets
        run: |
          bazel build //... --enable_bzlmod --enable_workspace

      - name: Verify build artifacts
        run: |
          ls -la bazel-bin/srv/
          ls -la bazel-bin/cli/
          ls -la bazel-bin/proto/

  # Test job (Bazel)
  test-bazel:
    name: Test Suite (Bazel)
    runs-on: ubuntu-latest
    needs: build
    if: always() && needs.build.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build all targets
        run: |
          bazel build //... --enable_bzlmod --enable_workspace

      - name: Run test suite
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Run individual test suites
        run: |
          echo "Running client unit tests..."
          bazel test //test/cli:client_test --test_output=all --enable_bzlmod --enable_workspace
          
          echo "Running server unit tests..."
          bazel test //test/srv:server_test --test_output=all --enable_bzlmod --enable_workspace
          
          echo "Running integration tests..."
          bazel test //test:integration_test --test_output=all --enable_bzlmod --enable_workspace

      - name: Generate test coverage
        run: |
          bazel coverage //test/cli:client_test //test/srv:server_test //test:integration_test --combined_report=lcov

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: bazel-testlogs/coverage/combined/lcov/coverage.dat
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Test job (CMake)
  test-cmake:
    name: Test Suite (CMake)
    runs-on: ubuntu-latest
    needs: [build, test-bazel]
    if: always() && needs.build.result == 'success' && needs.test-bazel.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build and test with CMake
        run: |
          chmod +x run_cmake_tests.sh
          ./run_cmake_tests.sh

      - name: Verify CMake build artifacts
        run: |
          ls -la build_cmake/
          ls -la build_cmake/server
          ls -la build_cmake/client

  # Multi-platform testing (Bazel)
  test-matrix-bazel:
    name: Test Matrix (Bazel)
    runs-on: ${{ matrix.os }}
    needs: [build, test-bazel, test-cmake]
    if: always() && needs.build.result == 'success' && needs.test-bazel.result == 'success' && needs.test-cmake.result == 'success'
    strategy:
      fail-fast: true  # Stop on first failure
      max-parallel: 1  # Run sequentially to prevent race conditions
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13]
        include:
          - os: ubuntu-20.04
            bazel-version: "6.0.0"
          - os: ubuntu-22.04
            bazel-version: "7.0.0"
          - os: macos-12
            bazel-version: "6.0.0"
          - os: macos-13
            bazel-version: "7.0.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bazel (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update
          sudo apt install -y bazel

      - name: Install Bazel (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install bazel

      - name: Setup C++ compiler (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Setup C++ compiler (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || true

      - name: Setup lcov (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y lcov

      - name: Setup lcov (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install lcov

      - name: Build all targets
        run: |
          # Use isolated Bazel cache to prevent race conditions
          bazel build //... --enable_bzlmod --enable_workspace --disk_cache=/tmp/bazel-cache-${{ matrix.os }}

      - name: Run tests
        run: |
          # Use isolated Bazel cache and test cache to prevent race conditions
          bazel test //test/cli:client_test //test/srv:server_test //test:integration_test --test_output=all --enable_bzlmod --enable_workspace --disk_cache=/tmp/bazel-cache-${{ matrix.os }} --test_output=errors

      - name: Cleanup Bazel cache
        if: always()
        run: |
          # Clean up isolated cache to prevent conflicts
          rm -rf /tmp/bazel-cache-${{ matrix.os }}
          bazel clean --expunge || true

  # Multi-platform testing (CMake)
  test-matrix-cmake:
    name: Test Matrix (CMake)
    runs-on: ${{ matrix.os }}
    needs: [build, test-bazel, test-cmake, test-matrix-bazel]
    if: always() && needs.build.result == 'success' && needs.test-bazel.result == 'success' && needs.test-cmake.result == 'success' && needs.test-matrix-bazel.result == 'success'
    strategy:
      fail-fast: true  # Stop on first failure
      max-parallel: 1  # Run sequentially to prevent race conditions
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Run setup script (macOS)
        if: runner.os == 'macOS'
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build and test with CMake
        run: |
          # Use isolated build directory to prevent race conditions
          export BUILD_DIR="build_cmake_${{ matrix.os }}"
          chmod +x run_cmake_tests.sh
          ./run_cmake_tests.sh

      - name: Cleanup CMake build
        if: always()
        run: |
          # Clean up isolated build directory to prevent conflicts
          rm -rf build_cmake_${{ matrix.os }}

  # Security and quality checks
  security:
    name: Security & Quality
    runs-on: ubuntu-latest
    needs: [build, test-bazel, test-cmake]
    if: always() && needs.build.result == 'success' && needs.test-bazel.result == 'success' && needs.test-cmake.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build all targets
        run: |
          bazel build //... --enable_bzlmod --enable_workspace

      - name: Run security scan
        run: |
          # Check for common security issues in BUILD files
          echo "Checking BUILD files for security issues..."
          find . -name "BUILD*" -exec grep -l "http_archive" {} \; | while read file; do
            echo "Checking $file for insecure URLs..."
            grep -n "http://" "$file" && echo "WARNING: Insecure HTTP URL found in $file" || true
          done

      - name: Check for hardcoded secrets
        run: |
          echo "Checking for potential secrets..."
          # Check for common secret patterns (more specific regex)
          if grep -r -E "(password|secret|api_key|token|auth_token)\s*=\s*['\"][^'\"]{12,}" . --exclude-dir=.git --exclude-dir=bazel-* --exclude-dir=build*; then
            echo "WARNING: Potential secrets found in code"
            exit 1
          fi

      - name: Validate protobuf files
        run: |
          echo "Validating protobuf files..."
          if command -v protoc >/dev/null 2>&1; then
            protoc --version
            protoc --proto_path=proto --cpp_out=/tmp proto/helloworld.proto
          else
            echo "protoc not available, skipping validation"
          fi

  # Performance testing
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [build, test-bazel, test-cmake, test-matrix-bazel, test-matrix-cmake]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.build.result == 'success' && needs.test-bazel.result == 'success' && needs.test-cmake.result == 'success' && needs.test-matrix-bazel.result == 'success' && needs.test-matrix-cmake.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x setup.sh
          echo "y" | ./setup.sh

      - name: Build with performance optimizations
        run: |
          bazel build //... --enable_bzlmod --enable_workspace --compilation_mode=opt

      - name: Run performance benchmarks
        run: |
          echo "Running performance tests..."
          # Start server in background
          bazel run //srv:server &
          SERVER_PID=$!
          sleep 5
          
          # Run client multiple times for performance testing
          for i in {1..10}; do
            time bazel run //cli:client
          done
          
          # Cleanup
          kill $SERVER_PID || true

  # Documentation validation
  docs:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check README links
        run: |
          echo "Checking README for broken links..."
          # This would require additional tools like linkchecker
          echo "README documentation check completed"

      - name: Validate setup script
        run: |
          chmod +x setup.sh
          # Test setup script syntax
          bash -n setup.sh
          echo "Setup script syntax is valid"

      - name: Validate test script
        run: |
          chmod +x run_tests.sh
          # Test run_tests.sh syntax
          bash -n run_tests.sh
          echo "Test script syntax is valid"

  # Final validation
  validate:
    name: Final Validation
    runs-on: ubuntu-latest
    needs: [build, test-bazel, test-cmake, test-matrix-bazel, test-matrix-cmake, security, docs]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          echo "Build job status: ${{ needs.build.result }}"
          echo "Bazel test job status: ${{ needs.test-bazel.result }}"
          echo "CMake test job status: ${{ needs.test-cmake.result }}"
          echo "Bazel matrix test job status: ${{ needs.test-matrix-bazel.result }}"
          echo "CMake matrix test job status: ${{ needs.test-matrix-cmake.result }}"
          echo "Security job status: ${{ needs.security.result }}"
          echo "Docs job status: ${{ needs.docs.result }}"
          
          # Check if any job failed and exit early
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ Build failed - stopping pipeline"
            exit 1
          fi
          
          if [[ "${{ needs.test-bazel.result }}" != "success" ]]; then
            echo "❌ Bazel tests failed - stopping pipeline"
            exit 1
          fi
          
          if [[ "${{ needs.test-cmake.result }}" != "success" ]]; then
            echo "❌ CMake tests failed - stopping pipeline"
            exit 1
          fi
          
          if [[ "${{ needs.test-matrix-bazel.result }}" != "success" ]]; then
            echo "❌ Bazel matrix tests failed - stopping pipeline"
            exit 1
          fi
          
          if [[ "${{ needs.test-matrix-cmake.result }}" != "success" ]]; then
            echo "❌ CMake matrix tests failed - stopping pipeline"
            exit 1
          fi
          
          if [[ "${{ needs.security.result }}" != "success" ]]; then
            echo "❌ Security checks failed - stopping pipeline"
            exit 1
          fi
          
          echo "✅ All checks passed!"
